### ISSUE TITLE
Study Logger. How to use it ?

### ISSUE THREAD

**Issue by dedu6ka** [lovac42/StudyLogger#2]
I like both of your ideas. I have been doing it manually; problem - many times I'd forget to do it. I expected your add-on to pop-up a message to VIew the Failed cards.  
As to the previewing NEW cards - it is of a tremendous value !!!! 
ANki hid this option in Custom deck ( which i stay away from ). 
It is a shame that ANki does not invite you to use both options -- by displaying the message BEFORE "Study Now" is clicked; and AFTER the Limits per day were reached. Instead poor medical students are directed to ... Custom deck ( to screw up their intervals and reset  the Learning cards). 
----------
I use Anki 2.0  
Downloaded the add-on. Restarted Anki. 
Purposly failed 3 new cards. 
Anki message "Your limits were reached ...." popped up.  
Here, i expected to see a question "Would you like to view the failed cards again in 'n - minutes ? 
------------------- 
Questions: 
1. I was not shown the Today's failed cards. 
2. There is no menu item either in Tools menu; or the Options menu.  
Please put more info in add-on Definition.  
Thanks for making one good add-on after another !

**Comment by lovac42** [comment]
This should create a menu called "Study". If you do not see "Study" in the menubar, then the addon may not be installed properly.

Under study, you will find options for the selected deck. You must select a deck, then choose study, and peek at new cards, or peek at review cards, or look at failed cards.
